### ISSUE TITLE
Setup Export of project to XCCDFs, Worksheets and InSpec Compliance Profiles

### ISSUE THREAD

**Issue by rbclark** [mitre/vulcan#105]
Once a project is completed, users will need to be able to export it to a beneficial format. We need to support the following:

 - [ ] Export project to XCCDF bundle: (any STIG from here is an example: https://public.cyber.mil/stigs/downloads/)
 - [ ] Export project to worksheets
 - [ ] Export projects to InSpec profiles

**Comment by Bialogs** [comment]
Ended up creating separate issues for each export type.
