### ISSUE TITLE
App-wide search by SRG ID

### ISSUE THREAD

**Issue by Bialogs** [mitre/vulcan#137]
Users should be able to search across the application for SRG IDs.

Search results need to include all the places that the particular control is being utilized.

For example, an SRG ID is searched for. The results return:
* A project that contains a component that includes a control with matching ID
* The component with control with matching ID
* The control with matching ID

**Comment by rbclark** [comment]
I believe this will only search released components at first since searching unreleased is going to pose some difficulty.
