### ISSUE TITLE
Ability to start a new revision of a STIG

### ISSUE THREAD

**Issue by Bialogs** [mitre/vulcan#138]
Copy existing project into a new project.

**Comment by timwongj** [comment]
@rlakey does this mean purely duplicating a project or something more specific such as copying over all the components from one project to another?

**Comment by rlakey** [comment]
Use case here is to support copying content from one project to another, for example, a Photon 3.0 project to a Photon 4.0 project to use the existing content as a basis for the target project.

Requirements:

- Copy a component from one project to another
- Ability to update the underlying SRG version if a newer version is available. Updates will potentially involve added/updated/removed requirements. This should also be possible on a intra project component copy.
- Potentially copy comments and revision history
- Updating STIG ID prefixes for copied components across projects. For example PHTN-30 to PHTN-40 while retaining the rest of the STIG ID itself. PHTN-30-000001 to PHTN-40-000001.
- Retain marked as duplicate links and duplicated controls
- Retain any custom fields added to components and metadata

**Comment by timwongj** [comment]
Configurable - don't update title, vuln desc, check/fix, other configurable fields
Other statuses - update
