### ISSUE TITLE
Ability to create a high-level version/release history document for a component/project.

### ISSUE THREAD

**Issue by Bialogs** [mitre/vulcan#143]
This is not fine-grained diff, but a high level diff of things add/removed/changed

**Comment by rlakey** [comment]
Assumptions:

- Given a project there has been an initial release of a component or components.
- At some point a component or components has been copied to a new component for updates
- Release history could be on a per project or per component basis
- For public consumption and should only include Applicable - Configurable controls
- High level.  Add/Remove/Update  Example: PHTN-30-000001 was updated. PHTN-30-000001 was added. PHTN-30-000001 was deleted.
