### ISSUE TITLE
Redesign Edit Control Page

### ISSUE THREAD

**Issue by rbclark** [mitre/vulcan#145]
<img width="1788" alt="Screen Shot 2021-01-13 at 3 50 17 PM" src="https://user-images.githubusercontent.com/2308869/104509031-197e0f00-55b7-11eb-9367-17a5b15e8616.png">

1. Remove "Filter NIST Family"
2. Change "Select Control" headings to not be V Numbers and instead be STIG IDs or some other identifier.
3. Do not show 4 tabs on "Build Control", instead allow for editing all data at once.
4. Add tabs, allowing users to quickly switch between the controls they are currently editing, in place of the words "Build Control".

**Comment by jkufro** [comment]
This comment is meant to capture sub-tasks for implementing control editing

- [ ] should be able to link and unlink controls to other existing controls (as a ??? role)
- [ ] should be able to select control applicability from a dropdown of (Applicable - Configurable, Applicable - Does Not Meet, Applicable - Inherently Meets, Not Applicable)
    - [ ] Anything selected other than "Applicable - Configurable" should only make the Justification field available to edit (see wireframes
- [ ] should be able to add and remove relevant links to a control composed of a title and http link
- [ ] should be able to duplicate a control (as a ??? role)
- [ ] should be able to delete a control (as a ??? role)
- [ ] should be able to lock as control (as a ??? role)
- [ ] should be able to leave/read comments on a control
- [ ] should be able to view the history of edits to a control (limited to specific tracked fields?)
- [ ] should be able to revert a change to a control to a previous version (as a ??? role?)
- [ ] should be able to search index view of controls with free text (based on ??? fields)
- [ ] should be able to filter index view of controls based on pre-defined criteria (control applicability, ???)
- [ ] should be able to

**Comment by jkufro** [comment]
Current state of wireframes (subject to change):
![Slide12](https://user-images.githubusercontent.com/24628687/128927232-ffa5595c-b13e-462f-be5b-70b394eade8d.jpeg)
![Slide13](https://user-images.githubusercontent.com/24628687/128927237-24f4dae6-0f3c-482c-af57-5980cadd4189.jpeg)
![Slide14](https://user-images.githubusercontent.com/24628687/128927238-279cc3f6-75b5-4f6f-bf3e-f6f9d12c0816.jpeg)
![Slide15](https://user-images.githubusercontent.com/24628687/128927241-fcc42702-c3dc-4c7d-8265-d46fe288d662.jpeg)
![Slide16](https://user-images.githubusercontent.com/24628687/128927245-d6d0f53e-dcc8-4e2e-bef5-b42e7531d543.jpeg)
![Slide17](https://user-images.githubusercontent.com/24628687/128927248-6f127b9a-2e69-4071-bdc9-0d004b3c749b.jpeg)

**Comment by jkufro** [comment]
> Feedback:
> 
> * ~Make it more obvious which fields changed on the revert field~ ([Additional visual aid to see which fields change in revert modal #221](https://github.com/mitre/vulcan/pull/221))
> * Advanced section on Rule edit page that shows everything other than what is commonly edited in VMware example spreadsheet
> * Mark what is required and optional for each Rule form element (XCCDF required and Application required)

https://github.com/mitre/vulcan/pull/227 should address the second bullet
