### ISSUE TITLE
Duplicate a Control

### ISSUE THREAD

**Issue by Bialogs** [mitre/vulcan#246]
Need the ability to duplicate a control.

Upon duplication the the `IAControl` field should be set to CCI 336 vendor best practices

**Comment by jkufro** [comment]
By `IAControl` field do you mean `ia_controls` should be changed on each disa rule description for the rule?

```ruby
new_rule.disa_rule_descriptions.each {  |description| description.ia_controls = 'CCI 336'}
```

**Comment by Bialogs** [comment]
Doesn't seem like IAControl needs to be updated after today's discussion
