### ISSUE TITLE
STIG ID assignment should be ordered by SRG ID

### ISSUE THREAD

**Issue by rlakey** [mitre/vulcan#301]
When assigning STIG IDs to a new component the assignment should be done in the order of SRG ID.

It appears DISA does not always order things this way in the XCCDF so this will cause confusion on STIG ID ordering when exported to CSV/XLSX for DISA which is sorted by SRG ID.

An example of this is in the Container Platform SRG where if you order by Vul/Rule ID or the order in which they are in the XCCDF then there is one SRG ID not in order as seen in the screenshot below.

SRG-APP-000516-CTR-000790 in this case is in reality much further down the list if sorted by SRG ID and would get a STIG ID ending in 165 instead of 104 as it currently does.

![image](https://user-images.githubusercontent.com/14838339/142256451-c86bd217-d191-4eb9-a6c1-695cb2a6af75.png)

**Comment by rbclark** [comment]
Fixed by #327
