### ISSUE TITLE
Rule comments should be visible on the sidebar in read only view

### ISSUE THREAD

**Issue by rbclark** [mitre/vulcan#317]

**Comment by timwongj** [comment]
1. Currently, the component comments/histories are shown on the sidebar in read only view, should that be replaced or should another additional column just be added for the rule comments/histories?
2. Should these comments only be viewed by certain users?

**Comment by rbclark** [comment]
1. I would say don't replace, just add it at the bottom of the current column if that's possible.
2. All users should be able to view the comments.

**Comment by timwongj** [comment]
Should users be able to add reviews/comments from here too or should it be read only?

![Screen Shot 2021-12-08 at 3 00 11 PM](https://user-images.githubusercontent.com/9956561/145275981-39fbc1e7-6eb0-458d-9c7d-321f19006f67.png)

**Comment by rbclark** [comment]
I'd say leave it read only since the rest of the page is
