### ISSUE TITLE
Add ability to filter which components are exported for XLS export

### ISSUE THREAD

**Issue by rbclark** [mitre/vulcan#330]
Currently all released components are exported with no ability to filter.

**Comment by timwongj** [comment]
what criteria did we want to be able to filter by again? was the idea to have a table view and checkboxes to indicate which components to export?

**Comment by rbclark** [comment]
> what criteria did we want to be able to filter by again? was the idea to have a table view and checkboxes to indicate which components to export?

That is correct, the user should have the ability to select which components they want to export before the export runs.

**Comment by timwongj** [comment]
@rlakey and I have decided to close this issue for now
