### ISSUE TITLE
389 Integrate Slack With Vulcan

### ISSUE THREAD

**Issue by aaronlippold** [mitre/vulcan#389]

**Comment by smarlaku820** [comment]
### Integrating Slack with Vulcan
Ability to send the following notification items to a private slack channel.

_Project_
- Project Creation
- Project Removal
- Project Renaming
_Component_
- Component Creation
- Component Removal
_SRG_
- SRG Upload
- SRG Removal
_Vulcan Admin_
- Assigning Vulcan Admin
- Removing Vulcan Admin
_Membership Notifications (Project)_
- Add member
- Update member role
- Remove member
_Membership Notifications (Component)_
- Add member
- Update member role
- Remove member

**Comment by smarlaku820** [comment]
Project Related Notifications (Screenshots Attached)
- We can see the items are hyperlinked and once clicked it can land users directly land on the respective project page.
<img width="535" alt="project_notifs" src="https://user-images.githubusercontent.com/34048837/225650926-c0b708c4-f19a-4350-b241-dc7f63d67161.png">

**Comment by smarlaku820** [comment]
SRG Related Notifications (Screenshots Attached)

<img width="434" alt="Screenshot 2023-03-16 at 8 12 55 PM" src="https://user-images.githubusercontent.com/34048837/225653105-77006359-da74-4f89-94c7-b8559fb1a8fc.png">

**Comment by smarlaku820** [comment]
Assigning/Removing Vulcan Admins to Users

<img width="404" alt="vulcan_admin" src="https://user-images.githubusercontent.com/34048837/225654263-ae2e1896-c294-4bc6-bc39-b5ee2b3b934c.png">

**Comment by smarlaku820** [comment]
Project Permissions

<img width="451" alt="Project Permissions" src="https://user-images.githubusercontent.com/34048837/225656278-a8c7b594-e2a0-4a20-878f-7e14d1cffeee.png">

Component Permissions

<img width="417" alt="Component Permissions" src="https://user-images.githubusercontent.com/34048837/225656607-980b2cee-36df-4456-9a6a-93ddc0b45d2e.png">
