### ISSUE TITLE
RFC: update to use the 4.x/5.x data features

### ISSUE THREAD

**Issue by aaronlippold** [mitre/vulcan#39]
- [ ] defaults to text based impacts: `none`,`low`,`medium`,`high`,`critical`
- [ ] uses `desc 'sub-section`, 'text` for: `check`,`fix`,`justification`,`vulnerability discussion`, etc[]
- [ ] puts attributes in the `inspec.yml` file and uses the `shared attributes` model
- [ ] has the ability to `remember` what attributes have been created already for easy reuse
- [ ] uses the `supports: <platform>` in the `inspec.yml`
- [ ] adds both a `single line` profile title and a `long desc` with in the `inspec.yml`
- [ ] correctly populates all the values in the `inspec.yml` template

**Comment by rbclark** [comment]
Is there an InSpec profile created somewhere that already uses all these elements that I can use for reference to make sure the output generated by Vulcan looks correct?

**Comment by aaronlippold** [comment]
Windows 10 on the mitre GitHub.

**Comment by Bialogs** [comment]
I think this is more applicable for `inspec_tools`

**Comment by aaronlippold** [comment]
just want to make sure we use our style guide when we generate profiles

--------
Aaron Lippold

***@***.***

260-255-4779

twitter/aim/yahoo,etc.
'aaronlippold'
