### ISSUE TITLE
Deleting a control prevents the deleting of the component

### ISSUE THREAD

**Issue by freddyfeelgood** [mitre/vulcan#429]
When deleting a control, the "deleted at" field on the "base_rules" table gets set with a timestamp of the deletion date (logical delete).  When the controls are loaded (from various means), there is a filter for 'WHERE base_rules.deleted_at IS NULL'.  When the delete for the component is triggered, it misses the items where deleted_at is not null, and produces the foreign key constraint error.

Steps to reproduce:
1. Open a set of controls in edit mode for a given component.
2. Choose a control, and click the red "delete control" button, then confirm the deletion.
3. Navigate back to the project, then click the delete icon (Remove Component) on the component. Confirm the removal.
4. Error 500 occurs because of a foreign key constraint violation.

In a dev environment, I was able to work around the issue by setting the deleted_at for the controls in question back to null, which allowed me to delete the component in question from the front end UI.

**Comment by timwongj** [comment]
Thanks for bringing this up, will put out a fix for it soon!
