### ISSUE TITLE
Have Vulcan automatically list all available STIGs/SRGs

### ISSUE THREAD

**Issue by wdower** [mitre/vulcan#480]
SAF team wrote some (unmaintained) code at https://github.com/mitre/inspec-profile-update-action that generated a JSON of all STIGs/SRGs published on public.cyber.mil and links to them (see stigs.json).

It would be nice if the "Upload an SRG" modal would keep a copy of the JSON and show you all the possible XCCDF files you could import.

Would likely take some dev time to determine best way to ingest that JSON, and on what schedule (biweekly?)

**Comment by rlakey** [comment]
For SRGs I would just note that not all of them are published publicly and not to make this connectivity a requirement to use Vulcan as I'm sure some deployments will not have access to query this list.

**Comment by vanessuniq** [comment]
> We could collect the data as part of the build process and store it locally - and if there is a connection - use that to see if their are any updates, and if so, update the local data?

My next PR will handle this. I added a cron job to pull the data biweekly
