### ISSUE TITLE
Output Vulcan logs to stdout

### ISSUE THREAD

**Issue by rlakey** [mitre/vulcan#514]
Currently the events in the log/production.log file are not output to stdout as well so they are not captured when looking at the Vulcan containers logs.

Requesting we also send these logs to stdout so they are accessible via kubectl logs and captured by log monitoring for the Vulcan containers.

**Comment by vanessuniq** [comment]
I think you will need to set the appropriate environment variable (RAILS_LOG_TO_STDOUT=1) to enable redirecting logs to stdout.

**Comment by rlakey** [comment]
That works. Thanks @vanessuniq
