### ISSUE TITLE
Update Role Permissions

### ISSUE THREAD

**Issue by rbclark** [mitre/vulcan#59]
It is currently difficult to use the application as a newcomer due to some intricacies with the current role setup. In order to make it easier to use, the following changes should be made:

  As an Admin I can:
  * See all projects and statuses
  * See everything
  * Approve anything

**Comment by rbclark** [comment]
Also should investigate https://github.com/varvet/pundit as a potential alternative to rolify here, pundit seems more up to date and provides nice separation between permissions and logic.

**Comment by Bialogs** [comment]
We need to consider the additional roles:

* Editor - ability to edit comment and mark controls as needing a review, no ability to sign-off or approve
* Reviewer - ability to approve of changes to a control, request changes
* Project Admin - full control over a project including locking discussions, reverting controls to previous state, users management of their project

**Comment by Bialogs** [comment]
No need to implement Organization, maintainer, Sensitive roles

**Comment by Bialogs** [comment]
Users have an overall roll for Vulcan that allows them to perform certain actions (TBD, but some examples may be full administration, creating new projects, importing SRGs, etc.)
Users have a project specific role that allows them to, for example, Lock/Unlock controls added to that project, revert a control to a point in history, etc.

**Comment by jkufro** [comment]
> Users have an overall roll for Vulcan that allows them to perform certain actions (TBD, but some examples may be full administration, creating new projects, importing SRGs, etc.)
> Users have a project specific role that allows them to, for example, Lock/Unlock controls added to that project, revert a control to a point in history, etc.

@Bialogs @rbclark Am I reading this correctly as 1 role per user and 1 user per project?

**Comment by Bialogs** [comment]
1 App level role per use and 1 project level role per user (2 "roles" total)
