### ISSUE TITLE
Update inspec after copying or duplicate a component

### ISSUE THREAD

**Issue by rlakey** [mitre/vulcan#598]
When copying or duplicating a component the resulting InSpec code for each control that satisfy other requirements does not have updated tags.

For example

<img width="773" alt="image" src="https://github.com/mitre/vulcan/assets/14838339/38388434-6558-462e-aeee-a78d0c58f855">

**Comment by vanessuniq** [comment]
There is no issue with the Duplicate workflow. The issue is with the copy workflow. 
@rlakey  What is the difference between copy and duplicate. What was the intent for each?
