### ISSUE TITLE
Create User/Role UX

### ISSUE THREAD

**Issue by aaronlippold** [mitre/vulcan#62]
Create frontend components that allow for management of Users.

**Comment by Bialogs** [comment]
Users have an overall roll for Vulcan that allows them to perform certain actions (TBD, but some examples may be full administration, creating new projects, importing SRGs, etc.)
Users have a project specific role that allows them to, for example, Lock/Unlock controls added to that project, revert a control to a point in history, etc.

**Comment by jkufro** [comment]
What are the exact management actions that are needed? 

I'm assuming admins be the only ones able to mange users?
