### ISSUE TITLE
Test existing LDAP config

### ISSUE THREAD

**Issue by rx294** [mitre/vulcan#70]

**Comment by rbclark** [comment]
Existing LDAP configuration works fine, however it has the following annoyances with it:

1. It must be configured in a configuration file on disk. I'm not sure if that will be a problem for deployment or not. It could be reconfigured to use database settings (it would require a restart after the database settings are updated).
1. When a user login fails, they are shown no error message and taken to a completely different login screen with no reason provided.
1. The login screen is unnecessarily complicated, and the database structure is as well. There is no need for an ldap_user model and a user model, we can just have 1 model and therefore 1 login box.
<img width="1282" alt="Screen Shot 2020-04-15 at 10 15 29 AM" src="https://user-images.githubusercontent.com/2308869/79347759-0b08a700-7f02-11ea-8e3c-cd140f84e546.png">
This is how it looks after failed login:
<img width="1174" alt="Screen Shot 2020-04-15 at 10 41 44 AM" src="https://user-images.githubusercontent.com/2308869/79350634-b535fe00-7f05-11ea-88f6-d40d311f3805.png">
Ideally, this is how it would look (where users can login with LDAP or non-LDAP credentials using the same screen):
<img width="1764" alt="Screen Shot 2020-04-15 at 10 44 37 AM" src="https://user-images.githubusercontent.com/2308869/79351004-237ac080-7f06-11ea-87e1-34c48bf5f0d2.png">
