### ISSUE TITLE
Edit Controls shows ability to reorder controls but it doesn't work

### ISSUE THREAD

**Issue by rbclark** [mitre/vulcan#74]
<img width="294" alt="Screen Shot 2020-04-15 at 12 32 51 PM" src="https://user-images.githubusercontent.com/2308869/79370616-fdaee500-7f20-11ea-8034-6833dc7eee16.png">

Dragging these to reorder does nothing, the element just returns to its original location once you let go. This also really distracts from the actual thing that you need to do with the controls, which is click on them to edit.

**Comment by aaronlippold** [comment]
Odd, I have seen this work in demos ... lol ...
--------
Aaron Lippold

lippold@gmail.com

260-255-4779

twitter/aim/yahoo,etc.
'aaronlippold'

**Comment by rbclark** [comment]
Is there a valid reason to support reordering of controls? It seems to just detract from the actual purpose which is to edit controls.
