### ISSUE TITLE
Figure out actually useful text for homepage that will benefit a user who does not fully understand what Vulcan does.

### ISSUE THREAD

**Issue by rbclark** [mitre/vulcan#87]
Currently, `vulcan-next` has a block of text that provides users with a basic explanation of what Vulcan does. It is currently just filled with lipsum text:

<img width="1310" alt="Screen Shot 2020-05-19 at 9 01 17 AM" src="https://user-images.githubusercontent.com/2308869/82383272-78c15a80-99fb-11ea-940a-c52a1ea4071f.png">

We need some better text for this page.

**Comment by ejaronne** [comment]
How about: 

"Vulcan helps Subject Matter Experts (SMEs) apply Security Requirements Guides (SRGs) to author Security Technical Implementation Guides (STIGS) & corresponding InSpec Profiles as security testing content."

Did I miss anything?

**Comment by rbclark** [comment]
Thank you Eugene! I've gone ahead and added that now, and below that I've provided a spot for administrators to add any other administration related notes. I think that solves it well enough for now. (Fixed in https://github.com/mitre/vulcan/tree/vulcan-next)
<img width="1377" alt="Screen Shot 2020-05-20 at 10 45 27 AM" src="https://user-images.githubusercontent.com/2308869/82460329-05fdc100-9a87-11ea-8eac-76936336685d.png">
