### ISSUE TITLE
SRG Import

### ISSUE THREAD

**Issue by rbclark** [mitre/vulcan#94]
This feature was present in the Vulcan alpha, however it has not been ported over to the new vulcan master.

This feature currently duplicates a lot of code out inspec_tools, as part of porting this feature we should de-duplicate all of this code so that we do not have to maintain two instances of this code.

We also need tests for this feature validating that importing SRG's works correctly, as well as verification that all the associated SRG checks imported correctly as well.

Part of the current code used for SRG import: https://github.com/mitre/vulcan/blob/c2d81c40e665a2f88701d373b41a19fdf48f53ca/app/services/CCIAttributes.rb

Code in inspec_tools: https://github.com/mitre/inspec_tools/blob/b5178b1379759e5fa0e6c9769e829bf3df085491/lib/happy_mapper_tools/cci_attributes.rb

Functionally they seem to be the same, in fact most of the files in `app/services` in the Vulcan alpha app seem to be duplicates from inspec_tools.

**Comment by Bialogs** [comment]
Maybe we can consider a periodic job that will reach out to the website and scrape all the new ones.
